// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgaqTWpOmEwsh1dEARwhbcoU8pjkBw7dg',
    appId: '1:951261893915:web:6701390971d3b40a0bafbe',
    messagingSenderId: '951261893915',
    projectId: 'shoppinglist-e2fd2',
    authDomain: 'shoppinglist-e2fd2.firebaseapp.com',
    storageBucket: 'shoppinglist-e2fd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVdZMHUqN9JhCJumvrN4-RXCvc_F9nVc',
    appId: '1:951261893915:android:b2badc56ee6e27390bafbe',
    messagingSenderId: '951261893915',
    projectId: 'shoppinglist-e2fd2',
    storageBucket: 'shoppinglist-e2fd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5pvP29OaQRbyqviWoUEMZhZcD8M2cf1M',
    appId: '1:951261893915:ios:c97172c0e9d038ce0bafbe',
    messagingSenderId: '951261893915',
    projectId: 'shoppinglist-e2fd2',
    storageBucket: 'shoppinglist-e2fd2.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5pvP29OaQRbyqviWoUEMZhZcD8M2cf1M',
    appId: '1:951261893915:ios:c97172c0e9d038ce0bafbe',
    messagingSenderId: '951261893915',
    projectId: 'shoppinglist-e2fd2',
    storageBucket: 'shoppinglist-e2fd2.appspot.com',
    iosBundleId: 'com.example.testApp',
  );
}
